In [1]:
import pandas as pd

In [2]:
data = {"name":["a", "b", "c", "d", "a", "c"], "eng":[8,7,5,8,8,5], "hindi":[2,3,4,5,2,6]}

In [3]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    5      6

In [4]:
df["duplicated"] = df.duplicated()
df

  name  eng  hindi  duplicated
0    a    8      2       False
1    b    7      3       False
2    c    5      4       False
3    d    8      5       False
4    a    8      2        True
5    c    5      6       False

In [5]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    5      6

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [8]:
dataset = pd.read_csv('data/titanic.csv')

In [9]:
dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
dataset.duplicated().sum()

np.int64(0)